# Generated by Django 2.0.6 on 2018-07-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goovi_db',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('file', models.ImageField(upload_to='files')),
            ],
        ),
    ]
